<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>turtlebot_datasets</name>
  <version>0.0.2</version>
  <description>Datasets to be used with turtlebot waffle pi (ROS 2)</description>

  <maintainer email="guilherme.lawless@tecnico.ulisboa.pt">Guilherme Lawless</maintainer>
  <maintainer email="joaogquintas@tecnico.ulisboa.pt">Joao Quintas</maintainer>
  <maintainer email="joao.s.pinto@tecnico.ulisboa.pt">Joao Pinto</maintainer>

  <license>GPLv3</license>


  <depend>rclpy</depend>
  <depend>tf2_ros</depend>
  <depend>tf2_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>rosbag2_py</depend>
  <depend>rosbag2_storage</depend>
  <depend>python3-numpy</depend>

  <exec_depend>ros2bag</exec_depend>
  <exec_depend>rosbag2_transport</exec_depend>
  <exec_depend>turtlebot3_bringup</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
